### ISSUE TITLE
Amplification request form

### ISSUE THREAD

**Issue by eidolonnight** [WordPress/Marketing-Team#140] opened 2022-11-10 01:25 UTC
Thanks to the success of our social media efforts in 2022, one of the most requested tasks for Marketing has been “Can you amplify this?”

These requests typically fall under one of our active campaigns listed in [GitHub](https://github.com/WordPress/Marketing-Team/issues/7), and as part of our 2023 efforts, we’d like to streamline these requests by providing a [GitHub issue template](https://href.li/?https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). This template will guide requesters through the process of providing us with all the relevant information, and ideally content, for posting to our various social channels and possibly beyond (Ie. eMail newsletters, WordPress.org posts, etc.).

Template content is being discussed in this Make blog post: https://make.wordpress.org/marketing/2022/11/10/feadback-request-amplification-request-form/

**Comment by eidolonnight** [comment] 2022-11-10 01:28
Initial form thoughts:

- Issue title: The primary title field for which we are able to recommend a predefined format. Something like “[AMPLIFY] Title” might be useful for readily identifying these issues for triage.
- Label: The template allows for automatically applying labels, so the creation of a new label may make sense.
- Link to share: This would be the URL, if applicable, that requesters would like to share. We will need to provide some guidance around links we will and will not share.
- Suggested hashtag/campaign: This would be a dropdown of active campaigns and either short descriptions or links to descriptions.
- Suggested content: Here would be where requesters could recommend content, and is the perfect place to share @laurlittle's [brand writing guide](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/).
- Linked resources: These would be images and/or videos for sharing. In the case of video, we will likely need to provide upload instructions.
- Suggested platforms: A dropdown of possible platforms for sharing: [Twitter](https://twitter.com/WordPress/), [Facebook](https://href.li/?https://www.facebook.com/WordPress/), [Instagram](https://www.instagram.com/wordpress/), [Linkedin](https://href.li/?https://www.linkedin.com/company/wordpress/), [YouTube](https://href.li/?https://www.youtube.com/wordpress), [Pinterest](https://href.li/?https://www.pinterest.com/WordPress/), [Tiktok](https://href.li/?https://www.tiktok.com/@wordpress?), [Tumblr](https://href.li/?https://wordpress.tumblr.com/)
- Requested share date: It'd be good to ask when the requester would like to share information, in the case that it aligns with some event. We should also remind folks that we expect requests to come in at least a week ahead.
- Notes: Freeform notes area.

**Comment by eidolonnight** [comment] 2023-04-03 21:45
https://github.com/WordPress/Marketing-Team/pull/211 submitted.

**Comment by sereedmedia** [comment] 2023-04-04 00:57
Not sure where to comment for: https://github.com/WordPress/Marketing-Team/blob/issue-templates/.github/ISSUE_TEMPLATE/request-for-amplification-template.yml

So I'll comment here! Please direct me to a better spot if there is one.

- I think that this form is combining two disparate audiences. One is for Make teams to promote things, and the other is for marketing contributors who would be drafting content.

- I do not think that we should expect or even imply that the various Make team members who want to promote or amplify something should be responsible for drafting content or being versed in the Style Guide (or for deciding on distribution platforms). That is not part of the work they are contributing, and most of them are not marketers, nor writers, and many don't want to be. The "what do you want to promote" section should just allow the person filling out the form to put in summary/description of what they are wanting to promote. 

- The marketing team, who we _can_ expect to be well-versed in the Style Guide and appropriate platforms, can then take the submitted information and draft appropriate content, get additional information, etc.

- It's not clear to me what the proposed workflow[*](https://wordpress.org/news/2023/03/episode-52-phase-three-with-hector-prieto/) is, so I propose the following process:

`submission > creation of a GH issue (including submitter) > editing and drafting by marketing team on GH issue > final draft approved by designated party > publication of content by designated party > published links on GH issue (submitter will be notified) > close issue`

This way no matter who is doing the work, whether they are sponsored/unsponsored, internal to A8C or community, the work is happening openly and it is being documented. We can easily set deadlines for contribution as needed, perhaps automatically based on the data included in the form. And if no one has done any contribution when the designated person needs to publish, then they can draft as they see fit (while also documenting it).

This could actually solve some of the process/content vetting issues that came up in the most recent coffee break, while also providing a clear process for marketing WordPress.org as a whole.

**Comment by eidolonnight** [comment] 2023-04-06 18:06
> I do not think that we should expect or even imply that the various Make team members who want to promote or amplify something should be responsible for drafting content or being versed in the Style Guide (or for deciding on distribution platforms).

With the current iteration of the guide, I do not think it unreasonable for people to at least understand the WordPress voice and tone. While editing is expected, this guide helps submitters create requests that align with WordPress values and reduce the workload for those reviewing these submissions. If this proves overly burdensome, perhaps we can explore using a summarized version.

> It's not clear to me what the proposed workflow

I'm recommending that we keep the process loose for now, until we have a better understanding of how this form gets used. This first iteration is based on past conversations with those asking for amplification, the information they required from us, and the questions we asked of them. After some use, I assume this form will require iteration. I want this form to make these requests easier to make and easier to triage.

**Comment by sereedmedia** [comment] 2023-04-06 18:46
I totally agree that getting a system in place for marketing requests is essential. And I truly support this initiative @eidolonnight!

> I do not think it unreasonable for people to at least understand the WordPress voice and tone. While editing is expected, this guide helps submitters create requests that align with WordPress values and reduce the workload for those reviewing these submissions. If this proves overly burdensome, perhaps we can explore using a summarized version.

I actually think that **_is_** unreasonable to expect people from other teams to draft marketing content. They are not coming to the marketing team simply to get something posted that they have ready to ship. They are coming to the marketing team for ideas, languages, strategy, and general marketing know-how. Even just this being a component of the form is a "stopper". 

The people we want to fill out this form are contributing in other areas of the project. Doing the work on their non-marketing team is their main focus. Getting the information to the marketing team is an extra step towards openness and collaboration across teams and the community. Furthermore, they may not be English-first speakers, and even if they are, they may not be comfortable writing content (many developers and contributors are not), and they likely don't know about what the best social audience or post format is. (If they did, they would probably be contributing on the marketing team.)

So they show up to marketing team, in order to get help with marketing, from the marketers. And then the main form where we direct people to asks for posting dates, the social accounts they want, and the content pre-written in the proper WordPress voice? 

_That's not helpful at all._ It is asking those contributors to do their own marketing. Not only does that put an unfair burden and unrealistic expectations on other teams, and it also denies the marketing team contributors the opportunity to work on the marketing content and strategy.

If we truly want to make it easier and simpler for Make WordPress teams to share their ideas, proposals, announcements, and calls for testing, then we can let them tell the marketing team about it, and then the marketing team can do its part by doing some marketing. :)

Note: I also think that this format lends itself to the expectation that whatever is put in the form is what will be churned out on socials, and I don't think that is an accurate expectation on any level. But since I already disagree with the format's approach from a workflow perspective, the expectation component is just an additional layer.

> I'm recommending that we keep the process loose for now, until we have a better understanding of how this form gets used.

It seems that there is actually a process setup here from your earlier comment that this approach would "reduce the workload" of the people reviewing the submissions. Whether it is "loose" or not is likely subjective, but it would seem that you at least have some specific people who will be tasked with reviewing the submissions. And it would seem that those people need a reduced workload.

However, all of the community contributors on the marketing team that I know are looking for MORE opportunities to contribute their skills. Not less. In fact, that is why many folks have left the marketing team, including myself in the past:  there weren't enough opportunities to use their marketing skills.

I think this form is the perfect opportunity to setup a process in which the community marketing team can openly receive requests for amplification from the community and then ... market them. Win-win!

We could even make a bit of a form funnel for it, so after the marketing team works on the request, it can be submitted into a second form with specific dates, tags, and content. That still "reduces the workload" for those reviewing the final requests and scheduling the content. And since the people who do the actual posting (you and your team, presumably) will still have final say over the content, it's actually win-win-win!

So right now the process looks like:

- Amplification request form (general) >> Keyholders 

And I am proposing that it looks like this:

- Amplification request form (general) >> Community Marketing Team  >> Keyholders

And really, when you look at it that way, I think it is pretty obvious why it is so important for the Community Marketing team to be a part of this process. 

I'll make direct edit to the Amplification request form in the review, with the understanding that it would involve us making another form to deliver completed amplification content. 

Thanks for moving this process forward!

**Comment by courtneyr-dev** [comment] 2023-04-07 17:59
> Thanks to the success of our social media efforts in 2022, one of the most requested tasks for Stargate has been “Can you amplify this?”
> 
> These requests typically fall under one of our active campaigns listed in [GitHub](https://github.com/WordPress/Marketing-Team/issues/7), and as part of our 2023 efforts, we’d like to streamline these requests by providing a [GitHub issue template](https://href.li/?https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). This template will guide requesters through the process of providing us with all the relevant information, and ideally content, for posting to our various social channels and possibly beyond (Ie. eMail newsletters, WordPress.org posts, etc.).
> 
> Template content is being discussed in this Make blog post: https://make.wordpress.org/marketing/2022/11/10/feadback-request-amplification-request-form/

As this is marketing team related, can we omit the internal Automattic team name?

**Comment by eidolonnight** [comment] 2023-04-07 19:54
> can we omit the internal Automattic team name?

Sure can! I've updated my original comment. It's worth noting that when I started working on this months ago, the focus was primarily social platforms which only a handful of people have access to. As I started v1 of the issue form, it seemed only natural to include other platforms as well.

**Comment by jillb** [comment] 2023-04-26 22:14
Without reading others' comments, here is my feedback. :)

----

**Issue title** -> If this field name is changeable in github, I'd like to see this be more specific. "Marketing request", "Thing you'd like to promote", etc. Even just "Title" would be more clear for a user perspective.

**Linked resources** -> My understanding was that the Learn WordPress events had a standardized image. (example: https://secure.meetupstatic.com/photos/event/5/7/d/d/600_509842493.webp?w=750) If that's true, there should be a guideline attached for when I provide the image and when it will be created by the team?

**Suggested platforms** -> Two thoughts:
Can this be optional? Or provide a choice for "I'll let the marketing team decide"? :) What if the person doesn't really have a preference and just wants it to be out there and seen on whatever platforms it will likely perform the best?

Second thought: I'd probably want an option for "Twitter and whatever other places you think it'll perform the best." :)

**Requested share date**: For my events, I know that Marketing has put them out there multiple times. I don't know what exactly the number was or when they went out. If it's up to me to tell you, I will want some guidelines, please.

----

The rest of the fields in the "initial form thoughts" make sense to me. :)

There were some probably great, long comments after the initial form thoughts. If you'd like my thoughts on any other ideas that have come up, would you be willing to ask me just the individual item to be considered, please? :)

**Comment by jpantani** [comment] 2023-05-26 16:47
Really great dialogue here. Commenting here to cover a bunch of different feedback without citing anyone thing in particular.

First, I'll start by saying on other teams I've noticed that you don't have to be an [Insert Team Name] expert, but you come to those teams because you either have a 1) desire to learn more about that team's function to build your resume/skillset or 2) have an idea/observation you'd like promoted, vetted, or cross-validated by "experts."

This is the premise and spirit that I make my comments in. For example, we made a concerted effort last year to refer to campaigns as projects or initiatives. But some industry jargon is bound to be there.  

I like the idea suggested by some to soften the language around submissions. I think anyone can submit, Make marketers, other Make team members, etc. Some of the ideas I've heard voiced like simply calling it a "Marketing request" make it sound a little less stiff and a little less tech issue.

Speaking from an experience at a large e-commerce company I worked for previously, we had an internal creative focused on writing copy and graphic design. As site managers, we provided them with a messaging hierarchy (what's important and why) hero item visuals (sample imagery), and a CTA. This format was super accessible and allowed the minimum viable info to get something into the queue. The more info, the better the request, but it set a widely accepted and low threshold to keep the ship moving fast. But was I able to do a lot of that work myself to speed things up? Absolutely!

I think it's fair to ask folks coming into the marketing team space to make a concerted effort to get their content up. Referencing the Brand writing guide is a tool for the user that increases their chance of getting something picked up. (Much like writing an interesting Press Release) With AI tools, we can broaden the skillsets of folks coming to the team and looking to collaborate. I see this as reasonable. 

At the same time, this shouldn't be a blocker. If someone is unsure about what to write in the form, it's beneficial to understand the messaging hierarchy: what's the topic, what's the heart of it, and why's it important. Adding these resources in a "Bonus" or "Pro tip" kind of way could enable more people to make a more connected contribution, rather than just punting to someone else. As a marketing professional, I take pride in writing this type of stuff and believe many others do too. Let's empower others to do that. But let's do it in a supportive and helpful way. 

Naturally, these are just my two cents, but I have a loosely held, strong conviction that we should do our best to minimize the barriers to entry to making these requests but set a tenor on how to make an excellent request versus an MVP request.

**Comment by sereedmedia** [comment] 2023-05-26 21:53
Thanks for your comments on this @jpantani. I have a lots of thoughts to share, but if you don't mind, I have few questions to clarify my understanding of your perspective:

- In the framework you are referencing above, you say "anyone can submit, Make marketers, other Make team members, etc.". Once a submission is made, who/what receives the submitted requests?
- What is the subsequent path for the request?
- You reference a process including "an internal creative" and "site managers". What is the parallel to those concepts in the context of the Marketing team?
- What does "increases their chance of getting something picked up" mean to you in this context? 
- You mention "folks coming into the marketing team space". Can you please elaborate on what audience you are referring to here, and clarify what you mean by "marketing team space"?

Thanks again for getting this issue moving! I agree this tool has excellent potential to help streamline operations and fulfill the Marketing team's mission. I look forward to your response.

**Comment by eidolonnight** [comment] 2023-06-06 18:33
> And I am proposing that it looks like this: Amplification request form (general) >> Community Marketing Team >> Keyholders

I'm glad that @jillb joined us here, because her work is partly why I want to avoid a longer chain of people here. A simple "Hi, I'd like to get this post some exposure" request should not require numerous hand-offs. This form empowers those making requests with the information they need (information that would otherwise be communicated via drawn-out conversations in Slack), sets reasonable expectations, connects requestors to those with direct access to Sprout, and makes this all public and trackable.

> Issue title -> If this field name is changeable in github...

It is not.

> Suggested content: -> To clarify, suggested means I can recommend some things that I want to make sure get conveyed, but someone in Marketing will re-write it, yes? That would be the ideal.

Yes. The idea here is to get relatively on-brand content from submitters that can be edited/refined for publication. In the past we've had issues with large amounts of completely off-brand messages being submitted. I've updated the description to make this more clear and refer people to the Marketing Slack if they need more hands-on help. That may also have the nice benefit of livening up our Slack.

> Linked resources -> I don't love needing to provide images. I don't know the marketing image tone. I probably don't have access to the right kinds of images.

This is optional, and the guidelines vary by campaign, so it's difficult to get too specific here.

> Suggested platforms -> Two thoughts: First thought: Can this be optional? Or give me a choice for: "I'll let the marketing team decide"? :) What if the person doesn't really have a preference and just wants it to be out there and seen on whatever platforms it will likely perform the best?

Great idea! I've added this option.

> Requested share date: For my events, I know that Marketing has put them out there multiple times. I don't know what exactly the number was or when they went out. I think they were optimized by the Marketing team for when people would view them?

Yes. That can and should continue. This field is optional and people can also use the notes area for additional info (like needing multiple posts).

**Comment by eidolonnight** [comment] 2023-06-06 18:38
Thank you to everyone who spent time making and recommending edits to these forms. I've merged several changes and will now merge the pull request. As with anything we do, iteration can and will continue, especially as we use these issue templates and learn what is and isn't working.

**Comment by sereedmedia** [comment] 2023-06-06 18:49
This is on the docket for discussion at the next Coffee and Collaboration session and I am not okaying closing this or finalizing this form until we have clarified some things.

**Comment by sereedmedia** [comment] 2023-06-06 19:31
> connects requestors to those with direct access to Sprout, 

@eidolonnight this is specifically the part I am concerned about. By having this form feed directly to the "keyholders" you are bypassing the Marketing Team and preventing the Marketing Team from being being a part of this process. **That is not acceptable.**

> refer people to the Marketing Slack if they need more hands-on help. 

Additionally this. You are putting the Marketing Team in a "you can help if someone needs extra help" position. Going through the marketing team is not "numerous hand-offs. The Marketing Team is a part of the WordPress project structure and it deserves to be treated as such, whomever holds the keys to publishing. 

Before this form is put into use, I want there to be a CLEAR process that a request goes through and ensure that that process does not bypass the Marketing Team, however convenient that may be for folks with access to Sprout. I have not seen that yet. Please let me know if I missed that somewhere.

NOTE: There is definitely a bigger conversation here about the dual team structure and their (apparently) divergent goals, but we can wait to have that larger conversation at the Community Summit.

**Comment by sereedmedia** [comment] 2023-06-15 22:36
Per the Collaboration Sessions today, here is my proposed workflow for the Amplification form. There needs to be some detail worked out in terms of the form fields, but overall, it seemed like the folks on the call (@eidolonnight @jpantani @DanSoschin @bjmcsherry and myself) felt like this would create a  functional and transparent process for the Marketing Team, while still maintaining efficiency in processing requests.
![MakeWP-Marketing-Team-Amplification-Request-Process_proposed](https://github.com/WordPress/Marketing-Team/assets/28426780/2328b206-ccc0-464a-8d55-e5508dc40904)

**Closed** 2023-07-31 19:08 UTC
Labels: discussion
