### ISSUE TITLE
Get involved or Contribute tab for the About page — structure and the content

### ISSUE THREAD

**Issue by OlaIola** [WordPress/Marketing-Team#217] opened 2023-04-10 06:10 UTC
Core ticket: https://core.trac.wordpress.org/ticket/23348#comment:53

[Get involved Tab for the About page Draft »](https://docs.google.com/document/d/17mCtcAugdr3xMrgFKBPVEgxHUY34FpJ4i6yrZQJUtqY/edit?usp=sharing)

My initial suggestion was to represent all teams, then I think it is possible to show them from a user's role, talants, desires and abilities. But grouping teams or telling in short about all possible tasks is a lot of information in which users can be lost. So, I am suggesting to highlight the main difference: technical and non-technical areas with listed easiest tasks which can be accomplished and add a link to the Contributor orientation tool (which needs to be updated and restored). And non-technical areas need to be listed first.

If this will work well, we can bring more new people, but of course not all of them will become contributors and to raise conversion of this pipeline, we need to think throughout the whole new contributors journey from this page as starting point (and other possible places of initial contact) to moment when newcomer can contribute on a regular basic and already hooked in into the awesome community we have. And it looks like the [Mentorship program](https://make.wordpress.org/community/2023/03/10/launching-the-contributor-working-group-call-for-volunteers) can play an important role in this journey.

**Comment by OlaIola** [comment] 2023-05-06 20:50
I created PR with this page draft for everyone to see how it can look like. I believe that this way it will be more clear what content it needs and possibly will nudge developers to look at it and participate.

Trac ticket: [#23348](https://core.trac.wordpress.org/ticket/23348)  and the patch: [23348.3.diff](https://core.trac.wordpress.org/attachment/ticket/23348/23348.3.diff)

**Comment by OlaIola** [comment] 2023-05-28 07:39
I updated the [Get involved Tab for the About page Draft »](https://docs.google.com/document/d/17mCtcAugdr3xMrgFKBPVEgxHUY34FpJ4i6yrZQJUtqY/edit?usp=sharing)

Right now the to-do list looks like:
- Orientation tool update and placement somewhere consistent (Make)
- Dedicated page on Make
- Review and finalise this Tab content
- Ask the Design team to work on this Tab representation
- Add links
- Ask the Polyglots team to translate the tab
- Add/check that #contributor-day or some other dedicated channel is added to newcomers in Slack ‘Welcome’ workflow
- After release: Highlight on social media that this Tab is added

Some parts can be added or improved later. If we strive for perfection before going live, it can never happen.

**Comment by sereedmedia** [comment] 2023-05-31 22:11
re:
Orientation tool update and placement somewhere consistent (Make)
Dedicated page on Make


Update from meta team in today's meeting:

- For first iteration, use the Contribute Tab in core as the "landing page" for contribution, as opposed to a landing page content on make.wordpress.org/contribute
- Because the code for the contribution tool already exists, it is possible to have the Contribution Tool live at make.wordpress.org /contribute.
- Will need a code review and implementation by meta
- Will need a design update and implementing by design (I pinged Joen A. in meta), but would be good to bring it up at the next design meeting. Wednesday - June 7, 2023 @ 22:00 UTC (they meet every other week on Wednesday)

- [ ] Make a meta ticket to review/update the existing Contributor Tool code
- [ ] Work with design team to update design of Contributor Tool and design of Contributor Tool on the /contribute page
- [ ] Work with meta and design to implement the updated Contributor Tool into /contribute page


cc @OlaIola

**Comment by estelaris** [comment] 2023-06-20 18:30
For WCEU 2023, I asked the Make teams to answer some questions. The idea was to turn them into few posts to introduce the teams but we ran out of time and decided to turn the info into 7 emails for new contributors. Below is the content of each email

**Comment by estelaris** [comment] 2023-06-20 18:38
Email #1:  Welcome to Contributor Day

Hi [name], 

Thank you for signing up for Contributor Day at WCEU 2023. Most of the Make Teams will be present, as well as four community initiatives. 

You can get involved in whatever suits your skills and goals. On Thursday, contributing will happen all day, and the beauty of it is that you can continue contributing to the same team or move around, if you prefer.
If you are a New Contributor, we sent you a series of 7 emails explaining everything you need to know about the teams and Contributor Day. If you have contributed before but are not an expert, look for the Table Leads who will be happy to help you out.

And if you are an Expert Contributor or a Team Rep, take the time to mentor less experienced contributors. We make WordPress a better community when we all share our expertise and help others.

In any case, don’t forget your computer, notebook and pens. Bring a water bottle that you can refill in the venue. 

These are most important accounts you will need for contributing:

1. WordPress account 
2. WordPress Slack account - Follow the instructions
3. GitHub account
4. Gravatar.com If you’d like to use an image/avatar on your WordPress Profile, create an account on Gravatar.com using the same email that you have used on your WordPress account. This is a recommended step.

The schedule:

- 08.30 Registration
- 09.15 Opening and welcome
- 10.00 Contributing to WordPress
- 12.15 Group photo
- 12.30 Lunch
- 14.00 Contributing to WordPress
- 17.00 Teams summaries and wrap-up

To learn more about Contributor Day and specifics on each team go to the WCEU website. Please be aware that we are not allowed to bring food into the rooms but coffee and water are ok. 

If you have any questions, look for the people with blue WCEU t-shirts, we will be happy to help you.

See you in Athens,
The Contributor Day Organizing & Volunteer Team

**Comment by estelaris** [comment] 2023-06-20 18:41
Email #2: What to expect at WCEU Contributor Day as a first-time contributor

Dear first-time contributor,

Any Contributor Day can be overwhelming for first timers. Whether it’s the fact that half the people in there already know each other or that you feel clueless and do not know where to go or even amongst the sea of people.

Fear not! We have set up a table for first-time contributors where we will welcome and guide you through the process. Afterwards, a volunteer will walk you to your chosen team table and introduce you.

Contributor Day is a whole day event, and this is the schedule. 

08.30 Registration
09.15 Opening and welcome
10.00 Contributing to WordPress
12.15 Group photo
12.30 Lunch
14.00 Contributing to WordPress
17.00 Teams summaries and wrap-up

Some rules to follow:

Follow the Code of Conduct
Introduce yourself, network, ask questions, contribute, and above all, have fun! We work hard but we like to do it with a smile on our faces. Even though the event is all day long, you are free to leave at any time, and you are free to change tables too.
 
If you need anything, look for the volunteers with the blue WCEU t-shirts. We will be there to help you.

Saludos,
The Contributor Day Organizing & Volunteer Team

P.S. If you would like to read everything there is to know about Contributor Day, you can review the page [on the WCEU site](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=3496e54196&e=6d36e99d20).

**Comment by estelaris** [comment] 2023-06-20 18:45
Email #3: How can I contribute to WordPress?

Dear first-time contributor:

**Contributions to WordPress** can be done in many ways, it all depends on what you like and what your skills are. Of course, the most important part of WordPress is the software itself, there are many routes you can take.

WordPress is open to contributors from website designers, community managers, project managers, mobile developers, technical writers, UX designers, UI designers, typography specialists and so on. It is not a lie, we even have a surgeon and several retirees contributing. 

In order to participate, you need to set up some accounts on your computer. A tip from long-time contributors: always use the same email address for ALL your accounts. 

[WordPress account](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=85a42261a8&e=6d36e99d20) 
[WordPress Slack account](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=a57a920b3e&e=6d36e99d20) - [Follow the instructions](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=667bbf7ad7&e=6d36e99d20)
[GitHub account](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=b34acac0db&e=6d36e99d20)
[Gravatar.com](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=c9e437c4d3&e=6d36e99d20) If you’d like to use an image/avatar on your WordPress Profile, create an account on Gravatar.com using the same email that you have used on your WordPress account. This is a recommended step.

And lastly, review the [Contributor Handbook](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=3d884590e0&e=6d36e99d20).

Set this stuff up before Contributor Day and you will be ahead of the game ready for your first contribution in Athens!

If you would like to read everything there is to know about Contributor Day, you can review the page [on the WCEU site](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=366b9eb466&e=6d36e99d20).


Ciao,
The Contributor Day Organizing & Volunteer Team

**Comment by estelaris** [comment] 2023-06-20 18:49
Email #4: Introduction to the Make Teams

Dear first-time contributor:

Now that you are ready, how do you choose a team or table? The WordPress community organizes itself in teams, these are known as the Make Teams. Each team deals with something different within the community. 

There are 21 teams, so we will split them into 3 emails to give you more time to read and not overwhelm you with a ton of  information. A huge recommendation is to read the Contributor Handbook, which almost every team has, that will give you a better idea of what each team does and if it fits with your skills and interests. If any team uses specific software, we will link it below.

If you would like to read everything there is to know about Contributor Day, you can review the page [on the WCEU site.](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=a3f5822f64&e=6d36e99d20)

Mach’s gut!
The Contributor Day Organizing & Volunteer Team
 

### Accessibility
[Handbook](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=edec3376f8&e=6d36e99d20)

The accessibility team provides feedback on issues for people with disabilities across the WordPress project, including the block editor, admin, themes, etc. 

We're happy to help people in the Contributor Day to learn more about assistive technologies and web site accessibility in whatever area of WordPress they intend to work on.

If your goal is to join the Accessibility Team, a strong background in accessibility, assistive technology or web standards is important. 

There are two major paths to participating in the accessibility team: you can focus on contributing to other teams - such as editor, meta, or core - and join us for meetings to help keep us up to date on new developments and issues needing testing, or you can follow accessibility meetings so you're available to provide feedback and follow up on emerging accessibility issues.
 

### Community
[How to contribute to the community team](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=9ed8588af0&e=6d36e99d20)

The Community Team oversees official events, mentorship programs, diversity initiatives, contributor outreach, and other ways of growing the WordPress community.

The team will have discussions about our community related matters. Which includes various topics such as: How can we onboard / involve new contributors, Next Generation WordCamps, Discussions about DE&I, WordCamp Sponsorship Packages, how we can make the documentation for the community team better, exchanging ideas / knowledge with fellow Meetup organizers, etc.
 

### Core
[Handbook](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=dae612857d&e=6d36e99d20)

The core team contributes to the background code for  WordPress.

Join this table to write new code, update existing code, or even fix bugs.

This is for you if you know PHP, HTML, JavaScript or CSS – there are tasks for all levels.
 

### Core Performance
[Handbook](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=82b7545d67&e=6d36e99d20)

Download a code editor like [SublimeText](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=350493c946&e=6d36e99d20) or [VSCode](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=747d4f2c99&e=6d36e99d20)

The WordPress Core Performance Team is dedicated to monitoring, enhancing, and promoting performance in WordPress core and its surrounding ecosystem. We build and manage the [Performance Lab plugin](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=f549c102cd&e=6d36e99d20), a collection of performance-related “feature projects” for WordPress core, as well as other projects related to enforcing and monitoring performance best practices.

Contributors can work hands-on on performance related features, enhancements, or fixes for WordPress core, whether directly in the [WordPress core repository](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=108b09766c&e=6d36e99d20) or in the [Performance Lab repository](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=ebf35c3661&e=6d36e99d20). 


### CLI
[Handbook](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=f743d3d1b8&e=6d36e99d20)
[Contributing to WP CLI](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=9d1f7b8f62&e=6d36e99d20)

The CLI team is responsible for working on and maintaining the WP-CLI command-line tool. This tool allows a site administrator to control a WordPress installation via the command-line using scriptable commands (even remotely).

Contributor Day is usually about:

onboarding interested developers to make sure they have a working development setup on their machine that can successfully run the tests.
explaining the structure and philosophy of the WP-CLI and the ways in which it differs from WordPress Core development.
Finally get as many people as possible to their first "win" by having them create a pull-request (and hopefully even merging it during the contributor day).
 
### Design
[Handbook](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=815c761631&e=6d36e99d20)

[WordPress Component Library in Figma](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=8914dd0d34&e=6d36e99d20)

The design team focuses on the design of the WordPress.org site as well as the UI and UX for WordPress, including the Block Editor and the different blocks. 

If improving the user experience in WordPress is what you like, the design team will welcome you.


### Documentation 
[Handbook](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=678d205ac2&e=6d36e99d20)

[Access to the Documentation Issue Tracker](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=750df1a7b0&e=6d36e99d20)

The Documentation team is writing documentation on how to use WordPress for end-users and how to develop on top of WordPress for developers. 

We are famous for always having cookies at Contributor Days because nothing fuels the best documentation as good as sweet food does. We usually have a list of good first issues as well as more advanced tasks, all of which represent the highest priority tasks at the time. 

Having no prior knowledge and experience is extremely valuable to us because that’s the true test if our documentation is good and without any holes in explanation.

**Comment by estelaris** [comment] 2023-06-20 18:52
Email #5: Introduction to the Make Teams

Dear first-time contributor,

This is the second email on the **Make Teams**, as we mentioned in our previous email, we have split them into 3 emails to give you more time to read and not overwhelm you with so much information. A huge recommendation is to read the Contributor Handbook, which almost every team has, that will give you a better idea of what each team does and if it fits with your skills and interests. If any team uses specific software, we will link it below.

If you would like to read everything there is to know about Contributor Day, you can review the page [on the WCEU site](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=5ed0131e23&e=6d36e99d20).

Με εκτίμηση,
The Contributor Day Organizing & Volunteer Team
 

### Hosting
[Handbook](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=855da12098&e=6d36e99d20)

People in this team are closely related to the world of hosting. They work as system administrators, plugin developers etc., and are concerned about improving the relationship between WordPress and the hosting where they are hosted.

We usually work in the [Handbook and the Documentation](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=39e1465fe5&e=6d36e99d20), primarily the Advanced Administration handbook. If you work in a hosting company, or you are a sysadmin person, this is your place!
 

### Marketing
[Handbook](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=4dfee877c5&e=6d36e99d20)

The Marketing team promotes WordPress to current and future users and contributors. We create and amplify campaigns to support the growth of the WordPress project.

The Marketing team manages tasks via GitHub, so all of our contribution is based around that. After greeting our table leads, contributors will be asked to introduce themselves in the Marketing Slack channel and "check in" by leaving a comment on an introductory GitHub issue ([#225](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=3b5a05c793&e=6d36e99d20))

That GitHub issue will lead contributors on a choose-your-own-adventure style exploration through the open Marketing GitHub issues and discussions, where they are encouraged to comment, edit and create marketing materials, or provide ideas as needed.

We will have a few issues of special focus throughout the day. A more specific schedule will be available closer to the day of the event.
 

### Meta
[Handbook](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=2aa1463266&e=6d36e99d20)

The Meta team works on everything related to the websites used by the WordPress project itself, such as [WordPress.org](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=2e3406ec56&e=6d36e99d20), [WordCamp.org](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=72e4c66025&e=6d36e99d20), [Learn.WordPress.org](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=41f4cfdf0a&e=6d36e99d20), etc.

WordPress.org is the first touch point for most people when getting started with WordPress, and continues to be a highly valuable ongoing resource as they progress. Meta contributions improve that experience and value for new and seasoned WordPress folks alike.

The projects will be using a bundled development environment, and this will also require [Docker](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=ec8205f4eb&e=6d36e99d20), [Composer](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=b3c8689b3a&e=6d36e99d20), and [Node/NPM](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=802d918b83&e=6d36e99d20) to be installed. Experience with [WP Env](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=a872f09e32&e=6d36e99d20) is helpful.

In order to be able to start coding straight away, attendees should install and configure either [WordCamp](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=03dbec3634&e=6d36e99d20), [Learn](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=b010cb9221&e=6d36e99d20), or [Pattern Directory](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=d963a33a99&e=6d36e99d20).

Non code contributors will be able to help in other ways, for example working with issues on [Meta Trac](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=de5e60343a&e=6d36e99d20).

A code editor like [SublimeText](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=2500f5b824&e=6d36e99d20) or [VSCode](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=220d0cb9cf&e=6d36e99d20) is also useful.
 

### Mobile
[Handbook](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=77e52fb485&e=6d36e99d20)

For code contributors the following IDEs are recommended:

[Android Studio](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=a8f93afeb8&e=6d36e99d20) for [WordPress-Android](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=29392d8e18&e=6d36e99d20)
[XCode](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=9c46196dac&e=6d36e99d20) for [WordPress-iOS](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=e6bef7f98f&e=6d36e99d20) (a Mac is needed for this)
[VSCode](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=04423946a0&e=6d36e99d20) for [Gutenberg Mobile](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=ae407efc19&e=6d36e99d20) ([prerequisites](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=50a7a9c8b1&e=6d36e99d20))

The mobile team builds the iOS and Android WordPress mobile apps. The team also works on the mobile version of Gutenberg.

These are some ways to contribute:

Write and submit code. If you’re a developer, you can contribute to the app’s codebase by submitting pull requests through GitHub:
[WordPress for iOS](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=ba561b1b94&e=6d36e99d20) is ~80% Swift, with Objective C making up some parts of the codebase.
[WordPress for Android](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=8863b1be86&e=6d36e99d20) is written in Kotlin (~66%) and Java (~34%).
If React Native is your jam, you could consider contributing to the editing experience in both apps with [Mobile Gutenberg](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=1a7b1c9b8b&e=6d36e99d20).
 

### Photos

The [Photo Directory](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=6502b5ff30&e=6d36e99d20) team moderates every photo submitted to the WordPress Photo Directory, maintains and improves the directory site itself, and provides resources and documentation to educate, encourage, and facilitate photo contributors.

During Contributor Day, the team will be reviewing photos. Learning what makes a good photo, and what must be declined. 
 

### Polyglots
[Handbook](https://wordcamp.us4.list-manage.com/track/click?u=7fe71eec16a6ac55c86658a8e&id=7f1c803911&e=6d36e99d20)

The Polyglots team translates WordPress into more than 200 languages and language variants. The team also builds and maintains local translation communities, organises translation contributor sprints, and collaborates with the core and meta teams to ensure WordPress users have access to the software in their own language. 

During contributor day you will be encouraged to get in touch with your local translation team and after contributor day you can continue communicating with both your local and the global translation team in WordPress Slack
 

### Plugins

The plugins theme is being reorganized and they would like to focus on creating new onboarding documents

**Comment by estelaris** [comment] 2023-06-20 18:56
Email #7: What happens after Contributor Day?

**Keep in touch**: stay connected with the WordPress community by sticking around on Slack and joining the meetings. Also, engage in social media, it's a great way to stay up-to-date with news, updates, and announcements. You can also find your local community, and if there isn’t one - great, maybe get one started yourself! (Learn all about this at the Community Table during Contributor Day!)

**Use what you’ve learned**: apply the knowledge and skills you've gained during the event in your work and personal projects. Share your experience with others and encourage them to jump on WordPress for their web projects and join future WordCamp events.

**Give feedback:** we REALLY value your feedback and want to improve this event in the future. Please take a few minutes to complete our survey and share your thoughts, suggestions, and ideas.

Thank you for your participation at Contributor Day and enjoy WordCamp Europe 2023!

asante sana,
The Contributor Day Organizing & Volunteer Team

**Comment by estelaris** [comment] 2023-06-20 18:58
The questions, without edition, are in this [document](https://docs.google.com/document/d/19aC3kJF2PF0oSwUYub4K4taxvKVX3fhOHyST5EfF5A0/edit?usp=sharing)

**Comment by estelaris** [comment] 2023-06-20 19:31
Lessons learned during the organization of Contributor Day at WCEU 2023:

1. **Before the event,** as an organizer, one must:

- Talk to the Make Teams, join the meetings, ask questions and make suggestions. What do you need from them, what to expect, what information do you need and give them a deadline.
- Leaving messages in their Slack channel is not productive as they don't know what you need from the teams.
- Post information about CD on the WordCamp or Contributor Day website.
- If you receive questions from attendees, refer them to the Make Teams, they usually have the best answers
- Keep a list of New Contributors, email them, give them instructions, download software before the event
- Always answer attendees' questions
- Make sure that they are registered for CD. At WCEU main registration, there is a questions that says "do you plan to attend CD?" This question is only to give us an idea of how many people is interested in attending, doesn't mean that they are registered. If your WordCamp does the same, make sure you clarify the input to attendees, either with a post or social media.

2. During the event:

- Make a list and have an idea of how many contributors per team will there be. Numbers are more a calculation than a reality as many, especially new contributors, sign up for 4 or 6 teams.
- Print 1 extra card per team just in case. And always print cards without teams for emergencies.
- In the slideshow, mention only the teams that will be present at CD
- Thank your sponsors

3. After CD

- Send a thank you for attending contributor day email, mention the following:
- Thank you for attending
- What happens after CD (Keep in touch, use what you learned, give feedback)
- Meet the teams in Slack (link to the meetings page)

**Comment by courtneyr-dev** [comment] 2023-06-26 19:31
Helpful resources on Learn to link to:

- [https://learn.wordpress.org/lesson-plan/creating-joining-wordpress-slack-orientation-to-channels-and-etiquette/](https://learn.wordpress.org/lesson-plan/creating-joining-wordpress-slack-orientation-to-channels-and-etiquette/)
- [https://learn.wordpress.org/lesson-plan/creating-a-wordpress-org-account/#example-lesson](https://learn.wordpress.org/lesson-plan/creating-a-wordpress-org-account/#example-lesson)
- [https://learn.wordpress.org/tutorial/set-up-a-wordpress-org-account/](https://learn.wordpress.org/tutorial/set-up-a-wordpress-org-account/)

**Comment by OlaIola** [comment] 2023-07-01 18:23
When this tab will be finally in the Core, we can consider taking an interview from original ticker reporter:
https://profiles.wordpress.org/mt_suzette/

**Comment by courtneyr-dev** [comment] 2023-07-01 22:14
Suzette no longer uses that account from her days at Media Temple. However, I can help us get in touch with her still. I've shared with her that this ticket is getting attention now and she's delighted.

**Comment by sereedmedia** [comment] 2023-07-01 23:29
Haha, I spoke to Suzette yesterday about this! She used to be a cohost on my podcast before she left the community.

**Comment by sereedmedia** [comment] 2023-07-11 23:44
This is the final draft of the text for the Get Involved/Contribute tab: https://docs.google.com/document/d/1F2-75YqtZ2-15DWiNEc0Q6XYg0d-KS7tBFZlpkATbyk/edit

Pasting here for reference and posterity.

It's been reviewed by lots of people so ... all in all I am pretty sure this is DONE!!!!!!! 
__________________
Tab title: Get Involved

H1: Get Involved

H2: Be the future of WordPress
Do you use WordPress for work, for personal projects, or maybe even just for fun? You can help shape the long-term success of the open source project that powers millions of websites around the world. 

Join the WordPress contributor community and connect with others who are passionate about maintaining a free and open web.

- Be part of a global, open source community
- Apply your skills or learn some new ones
- Grow your network and make new friends

H2: Find your team 
Finding the area that aligns with your skills and interests is the first step toward meaningful contribution. With more than 20 Make WordPress teams working on different parts of the open-source WordPress project, there’s a place for everyone, no matter what your skill set is. 

H3: No-code contribution
WordPress may thrive on technical contributions, but you don’t have to code to contribute. Here are some of the ways you can make an impact without a single line of code:

- **Share** your knowledge in the WordPress support forums
- **Write** or improve documentation for WordPress 
- **Translate** WordPress into your local language
- **Create** and improve WordPress educational materials
- **Promote** the WordPress project to your community
- **Curate** photos or submit your own to the WordPress Photos Directory
- **Organize** or participate in local WordPress Meetups and WordCamps
- **Lend** your creative imagination to the WordPress UI design
- **Edit** videos and add captions to WordPress.tv
- **Explore** ways to reduce the environmental impact of millions of websites

H3: Code-based contribution 
If you do code, or want to, you can contribute technically in numerous ways:

- **Find** and report bugs in the WordPress core software
- **Test** new releases and proposed features for the block editor
- **Write** and submit patches to fix bugs or help build new features
- **Contribute** to the code, improve the UX, and test the WordPress app 

WordPress embraces new technologies, while being committed to backward compatibility. We use the following languages and libraries:

- Core and Block Editor: HTML, CSS, PHP, SQL, JavaScript, and React
- WordPress app: Kotlin, Java, Swift, Objective-C, Vue, Python, and TypeScript

H2: Help make WordPress better
Whether you speak at a local meetup, provide your perspective on a feature proposal, or submit a bug report, your contributions will make a difference.

Find your team → 
[link to make.wordpress.org/contribute]

**Comment by abhansnuk** [comment] 2023-09-29 02:33
Hi I have moved this from the to do for column to review in progress, to reflect Se’s last comment. There were contributors to this on the google doc, so it maybe that there are other things still happening. Is there any further help needed on this? Thanks @olalola

**Comment by sereedmedia** [comment] 2023-10-24 08:04
This is complete and this ticket can be closed!! Excellent work to all involved.

**Closed by sereedmedia** 2023-10-24 08:04 UTC
Labels: help wanted
